name: last_version
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  awesome_dialog: ^3.3.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^11.0.0
  cloud_firestore: ^6.6.0
  shared_preferences: ^2.5.5
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.2
  share_plus: ^13.2.0
  get_it: ^9.2.1
  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.1
  easy_localization: ^3.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

