// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyyCrmgr9p8BISGd-AC_aN_jET_elqAyY',
    appId: '1:113001888120:web:32a1c23cfc3621444ff08d',
    messagingSenderId: '113001888120',
    projectId: 'last-version-e4053',
    authDomain: 'last-version-e4053.firebaseapp.com',
    storageBucket: 'last-version-e4053.firebasestorage.app',
    measurementId: 'G-3B882LN37V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmaCKWHn0wqIeQs_cV0XMQWIdQJ-9392E',
    appId: '1:113001888120:android:fa57745a812eaa264ff08d',
    messagingSenderId: '113001888120',
    projectId: 'last-version-e4053',
    storageBucket: 'last-version-e4053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeAkagTHcaxhK8czNRgR2LJhNGAd4jlfE',
    appId: '1:113001888120:ios:d6daffd9814ad3e84ff08d',
    messagingSenderId: '113001888120',
    projectId: 'last-version-e4053',
    storageBucket: 'last-version-e4053.firebasestorage.app',
    iosBundleId: 'com.example.lastVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeAkagTHcaxhK8czNRgR2LJhNGAd4jlfE',
    appId: '1:113001888120:ios:d6daffd9814ad3e84ff08d',
    messagingSenderId: '113001888120',
    projectId: 'last-version-e4053',
    storageBucket: 'last-version-e4053.firebasestorage.app',
    iosBundleId: 'com.example.lastVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyyCrmgr9p8BISGd-AC_aN_jET_elqAyY',
    appId: '1:113001888120:web:685a7d286e6a08af4ff08d',
    messagingSenderId: '113001888120',
    projectId: 'last-version-e4053',
    authDomain: 'last-version-e4053.firebaseapp.com',
    storageBucket: 'last-version-e4053.firebasestorage.app',
    measurementId: 'G-ENLJXBLJKB',
  );
}
